### PR TITLE
Submit for code review

### PR DESCRIPTION
**Pull request by nachosala89**
Submitted To-Do List project for code review.

### CODE REVIEW

**Review by mustabbas — CHANGES_REQUESTED** [review]
Hi @nachosala89 
Good job so far!
There are some issues that you need to work on to go to merge this project but you are almost there!
### Required Changes 
Check the comments under the review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.

**Review by mustabbas — CHANGES_REQUESTED** [review]
Hi @nachosala89 
Good job so far!
There are some issues that you need to work on to go to merge this project but you are almost there!
### Required Changes 
Check the comments under the review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.

**Comment by mustabbas** [comment]
- [x] when I delete 1  task from the list all tasks delete you should delete the task only I delete.
https://github.com/nachosala89/copy-to-do-list/blob/f9b3d6929ac386334cade4eac852466a8dde02d5/src/listManager.js#L27-L30

**Comment by mustabbas** [comment]
- [x] when I delete the completes task all tasks delete also you should delete the completed task only.
https://github.com/nachosala89/copy-to-do-list/blob/f9b3d6929ac386334cade4eac852466a8dde02d5/src/showItems.js#L70-L76

**Comment by nachosala89** [comment]
Thank you for your suggestions! The problem was that I had the wrong Live version in the README.md file and I have updated it. Please feel free to check it again and to tell me if you find another issue.

**Comment by mustabbas** [comment]
Hi @nachosala89,

Your project is complete! There is nothing else to say other than... it's time to merge it 

✔️ Thanks for making the required changes. 👍

Congratulations! 🎉

**Review by mustabbas — APPROVED** [review]

**Comment by nachosala89** [comment]
Thank you! :smile:

**Pull request merged**
